CREATE TABLE IF NOT EXISTS CARMOTION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    worldPositionX FLOAT,
    worldPositionY FLOAT,
    worldPositionZ FLOAT,
    worldVelocityX FLOAT,
    worldVelocityY FLOAT,
    worldVelocityZ FLOAT,
    worldForwardDirX SMALLINT,
    worldForwardDirY SMALLINT,
    worldForwardDirZ SMALLINT,
    worldRightDirX SMALLINT,
    worldRightDirY SMALLINT,
    worldRightDirZ SMALLINT,
    gForceLateral FLOAT,
    gForceLongitudinal FLOAT,
    gForceVertical FLOAT,
    yaw FLOAT,
    pitch FLOAT,
    roll FLOAT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SESSION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    weather TINYINT UNSIGNED,
    trackTemperature TINYINT,
    airTemperature TINYINT,
    totalLaps TINYINT UNSIGNED,
    trackLength SMALLINT UNSIGNED,
    sessionType TINYINT UNSIGNED,
    trackId TINYINT,
    formula TINYINT UNSIGNED,
    sessionTimeLeft SMALLINT UNSIGNED,
    sessionDuration SMALLINT UNSIGNED,
    pitSpeedLimit TINYINT UNSIGNED,
    gamePaused TINYINT UNSIGNED,
    isSpectating TINYINT UNSIGNED,
    spectatorCarIndex TINYINT UNSIGNED,
    sliProNativeSupport TINYINT UNSIGNED,
    numMarshalZones TINYINT UNSIGNED,
    marshalZones0_zoneStart FLOAT, marshalZones0_zoneFlag TINYINT,
    marshalZones1_zoneStart FLOAT, marshalZones1_zoneFlag TINYINT,
    marshalZones2_zoneStart FLOAT, marshalZones2_zoneFlag TINYINT,
    marshalZones3_zoneStart FLOAT, marshalZones3_zoneFlag TINYINT,
    marshalZones4_zoneStart FLOAT, marshalZones4_zoneFlag TINYINT,
    marshalZones5_zoneStart FLOAT, marshalZones5_zoneFlag TINYINT,
    marshalZones6_zoneStart FLOAT, marshalZones6_zoneFlag TINYINT,
    marshalZones7_zoneStart FLOAT, marshalZones7_zoneFlag TINYINT,
    marshalZones8_zoneStart FLOAT, marshalZones8_zoneFlag TINYINT,
    marshalZones9_zoneStart FLOAT, marshalZones9_zoneFlag TINYINT,
    marshalZones10_zoneStart FLOAT, marshalZones10_zoneFlag TINYINT,
    marshalZones11_zoneStart FLOAT, marshalZones11_zoneFlag TINYINT,
    marshalZones12_zoneStart FLOAT, marshalZones12_zoneFlag TINYINT,
    marshalZones13_zoneStart FLOAT, marshalZones13_zoneFlag TINYINT,
    marshalZones14_zoneStart FLOAT, marshalZones14_zoneFlag TINYINT,
    marshalZones15_zoneStart FLOAT, marshalZones15_zoneFlag TINYINT,
    marshalZones16_zoneStart FLOAT, marshalZones16_zoneFlag TINYINT,
    marshalZones17_zoneStart FLOAT, marshalZones17_zoneFlag TINYINT,
    marshalZones18_zoneStart FLOAT, marshalZones18_zoneFlag TINYINT,
    marshalZones19_zoneStart FLOAT, marshalZones19_zoneFlag TINYINT,
    marshalZones20_zoneStart FLOAT, marshalZones20_zoneFlag TINYINT,
    safetyCarStatus TINYINT UNSIGNED,
    networkGame TINYINT UNSIGNED,
    numWeatherForecastSamples TINYINT UNSIGNED,
    weatherForecastSamples0_sessionType TINYINT UNSIGNED, weatherForecastSamples0_timeOffset TINYINT UNSIGNED, weatherForecastSamples0_weather TINYINT UNSIGNED, weatherForecastSamples0_trackTemperature TINYINT UNSIGNED, weatherForecastSamples0_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples0_airTemperature TINYINT UNSIGNED, weatherForecastSamples0_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples0_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples1_sessionType TINYINT UNSIGNED, weatherForecastSamples1_timeOffset TINYINT UNSIGNED, weatherForecastSamples1_weather TINYINT UNSIGNED, weatherForecastSamples1_trackTemperature TINYINT UNSIGNED, weatherForecastSamples1_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples1_airTemperature TINYINT UNSIGNED, weatherForecastSamples1_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples1_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples2_sessionType TINYINT UNSIGNED, weatherForecastSamples2_timeOffset TINYINT UNSIGNED, weatherForecastSamples2_weather TINYINT UNSIGNED, weatherForecastSamples2_trackTemperature TINYINT UNSIGNED, weatherForecastSamples2_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples2_airTemperature TINYINT UNSIGNED, weatherForecastSamples2_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples2_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples3_sessionType TINYINT UNSIGNED, weatherForecastSamples3_timeOffset TINYINT UNSIGNED, weatherForecastSamples3_weather TINYINT UNSIGNED, weatherForecastSamples3_trackTemperature TINYINT UNSIGNED, weatherForecastSamples3_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples3_airTemperature TINYINT UNSIGNED, weatherForecastSamples3_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples3_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples4_sessionType TINYINT UNSIGNED, weatherForecastSamples4_timeOffset TINYINT UNSIGNED, weatherForecastSamples4_weather TINYINT UNSIGNED, weatherForecastSamples4_trackTemperature TINYINT UNSIGNED, weatherForecastSamples4_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples4_airTemperature TINYINT UNSIGNED, weatherForecastSamples4_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples4_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples5_sessionType TINYINT UNSIGNED, weatherForecastSamples5_timeOffset TINYINT UNSIGNED, weatherForecastSamples5_weather TINYINT UNSIGNED, weatherForecastSamples5_trackTemperature TINYINT UNSIGNED, weatherForecastSamples5_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples5_airTemperature TINYINT UNSIGNED, weatherForecastSamples5_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples5_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples6_sessionType TINYINT UNSIGNED, weatherForecastSamples6_timeOffset TINYINT UNSIGNED, weatherForecastSamples6_weather TINYINT UNSIGNED, weatherForecastSamples6_trackTemperature TINYINT UNSIGNED, weatherForecastSamples6_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples6_airTemperature TINYINT UNSIGNED, weatherForecastSamples6_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples6_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples7_sessionType TINYINT UNSIGNED, weatherForecastSamples7_timeOffset TINYINT UNSIGNED, weatherForecastSamples7_weather TINYINT UNSIGNED, weatherForecastSamples7_trackTemperature TINYINT UNSIGNED, weatherForecastSamples7_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples7_airTemperature TINYINT UNSIGNED, weatherForecastSamples7_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples7_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples8_sessionType TINYINT UNSIGNED, weatherForecastSamples8_timeOffset TINYINT UNSIGNED, weatherForecastSamples8_weather TINYINT UNSIGNED, weatherForecastSamples8_trackTemperature TINYINT UNSIGNED, weatherForecastSamples8_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples8_airTemperature TINYINT UNSIGNED, weatherForecastSamples8_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples8_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples9_sessionType TINYINT UNSIGNED, weatherForecastSamples9_timeOffset TINYINT UNSIGNED, weatherForecastSamples9_weather TINYINT UNSIGNED, weatherForecastSamples9_trackTemperature TINYINT UNSIGNED, weatherForecastSamples9_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples9_airTemperature TINYINT UNSIGNED, weatherForecastSamples9_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples9_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples10_sessionType TINYINT UNSIGNED, weatherForecastSamples10_timeOffset TINYINT UNSIGNED, weatherForecastSamples10_weather TINYINT UNSIGNED, weatherForecastSamples10_trackTemperature TINYINT UNSIGNED, weatherForecastSamples10_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples10_airTemperature TINYINT UNSIGNED, weatherForecastSamples10_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples10_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples11_sessionType TINYINT UNSIGNED, weatherForecastSamples11_timeOffset TINYINT UNSIGNED, weatherForecastSamples11_weather TINYINT UNSIGNED, weatherForecastSamples11_trackTemperature TINYINT UNSIGNED, weatherForecastSamples11_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples11_airTemperature TINYINT UNSIGNED, weatherForecastSamples11_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples11_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples12_sessionType TINYINT UNSIGNED, weatherForecastSamples12_timeOffset TINYINT UNSIGNED, weatherForecastSamples12_weather TINYINT UNSIGNED, weatherForecastSamples12_trackTemperature TINYINT UNSIGNED, weatherForecastSamples12_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples12_airTemperature TINYINT UNSIGNED, weatherForecastSamples12_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples12_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples13_sessionType TINYINT UNSIGNED, weatherForecastSamples13_timeOffset TINYINT UNSIGNED, weatherForecastSamples13_weather TINYINT UNSIGNED, weatherForecastSamples13_trackTemperature TINYINT UNSIGNED, weatherForecastSamples13_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples13_airTemperature TINYINT UNSIGNED, weatherForecastSamples13_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples13_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples14_sessionType TINYINT UNSIGNED, weatherForecastSamples14_timeOffset TINYINT UNSIGNED, weatherForecastSamples14_weather TINYINT UNSIGNED, weatherForecastSamples14_trackTemperature TINYINT UNSIGNED, weatherForecastSamples14_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples14_airTemperature TINYINT UNSIGNED, weatherForecastSamples14_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples14_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples15_sessionType TINYINT UNSIGNED, weatherForecastSamples15_timeOffset TINYINT UNSIGNED, weatherForecastSamples15_weather TINYINT UNSIGNED, weatherForecastSamples15_trackTemperature TINYINT UNSIGNED, weatherForecastSamples15_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples15_airTemperature TINYINT UNSIGNED, weatherForecastSamples15_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples15_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples16_sessionType TINYINT UNSIGNED, weatherForecastSamples16_timeOffset TINYINT UNSIGNED, weatherForecastSamples16_weather TINYINT UNSIGNED, weatherForecastSamples16_trackTemperature TINYINT UNSIGNED, weatherForecastSamples16_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples16_airTemperature TINYINT UNSIGNED, weatherForecastSamples16_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples16_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples17_sessionType TINYINT UNSIGNED, weatherForecastSamples17_timeOffset TINYINT UNSIGNED, weatherForecastSamples17_weather TINYINT UNSIGNED, weatherForecastSamples17_trackTemperature TINYINT UNSIGNED, weatherForecastSamples17_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples17_airTemperature TINYINT UNSIGNED, weatherForecastSamples17_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples17_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples18_sessionType TINYINT UNSIGNED, weatherForecastSamples18_timeOffset TINYINT UNSIGNED, weatherForecastSamples18_weather TINYINT UNSIGNED, weatherForecastSamples18_trackTemperature TINYINT UNSIGNED, weatherForecastSamples18_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples18_airTemperature TINYINT UNSIGNED, weatherForecastSamples18_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples18_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples19_sessionType TINYINT UNSIGNED, weatherForecastSamples19_timeOffset TINYINT UNSIGNED, weatherForecastSamples19_weather TINYINT UNSIGNED, weatherForecastSamples19_trackTemperature TINYINT UNSIGNED, weatherForecastSamples19_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples19_airTemperature TINYINT UNSIGNED, weatherForecastSamples19_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples19_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples20_sessionType TINYINT UNSIGNED, weatherForecastSamples20_timeOffset TINYINT UNSIGNED, weatherForecastSamples20_weather TINYINT UNSIGNED, weatherForecastSamples20_trackTemperature TINYINT UNSIGNED, weatherForecastSamples20_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples20_airTemperature TINYINT UNSIGNED, weatherForecastSamples20_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples20_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples21_sessionType TINYINT UNSIGNED, weatherForecastSamples21_timeOffset TINYINT UNSIGNED, weatherForecastSamples21_weather TINYINT UNSIGNED, weatherForecastSamples21_trackTemperature TINYINT UNSIGNED, weatherForecastSamples21_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples21_airTemperature TINYINT UNSIGNED, weatherForecastSamples21_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples21_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples22_sessionType TINYINT UNSIGNED, weatherForecastSamples22_timeOffset TINYINT UNSIGNED, weatherForecastSamples22_weather TINYINT UNSIGNED, weatherForecastSamples22_trackTemperature TINYINT UNSIGNED, weatherForecastSamples22_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples22_airTemperature TINYINT UNSIGNED, weatherForecastSamples22_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples22_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples23_sessionType TINYINT UNSIGNED, weatherForecastSamples23_timeOffset TINYINT UNSIGNED, weatherForecastSamples23_weather TINYINT UNSIGNED, weatherForecastSamples23_trackTemperature TINYINT UNSIGNED, weatherForecastSamples23_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples23_airTemperature TINYINT UNSIGNED, weatherForecastSamples23_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples23_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples24_sessionType TINYINT UNSIGNED, weatherForecastSamples24_timeOffset TINYINT UNSIGNED, weatherForecastSamples24_weather TINYINT UNSIGNED, weatherForecastSamples24_trackTemperature TINYINT UNSIGNED, weatherForecastSamples24_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples24_airTemperature TINYINT UNSIGNED, weatherForecastSamples24_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples24_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples25_sessionType TINYINT UNSIGNED, weatherForecastSamples25_timeOffset TINYINT UNSIGNED, weatherForecastSamples25_weather TINYINT UNSIGNED, weatherForecastSamples25_trackTemperature TINYINT UNSIGNED, weatherForecastSamples25_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples25_airTemperature TINYINT UNSIGNED, weatherForecastSamples25_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples25_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples26_sessionType TINYINT UNSIGNED, weatherForecastSamples26_timeOffset TINYINT UNSIGNED, weatherForecastSamples26_weather TINYINT UNSIGNED, weatherForecastSamples26_trackTemperature TINYINT UNSIGNED, weatherForecastSamples26_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples26_airTemperature TINYINT UNSIGNED, weatherForecastSamples26_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples26_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples27_sessionType TINYINT UNSIGNED, weatherForecastSamples27_timeOffset TINYINT UNSIGNED, weatherForecastSamples27_weather TINYINT UNSIGNED, weatherForecastSamples27_trackTemperature TINYINT UNSIGNED, weatherForecastSamples27_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples27_airTemperature TINYINT UNSIGNED, weatherForecastSamples27_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples27_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples28_sessionType TINYINT UNSIGNED, weatherForecastSamples28_timeOffset TINYINT UNSIGNED, weatherForecastSamples28_weather TINYINT UNSIGNED, weatherForecastSamples28_trackTemperature TINYINT UNSIGNED, weatherForecastSamples28_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples28_airTemperature TINYINT UNSIGNED, weatherForecastSamples28_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples28_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples29_sessionType TINYINT UNSIGNED, weatherForecastSamples29_timeOffset TINYINT UNSIGNED, weatherForecastSamples29_weather TINYINT UNSIGNED, weatherForecastSamples29_trackTemperature TINYINT UNSIGNED, weatherForecastSamples29_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples29_airTemperature TINYINT UNSIGNED, weatherForecastSamples29_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples29_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples30_sessionType TINYINT UNSIGNED, weatherForecastSamples30_timeOffset TINYINT UNSIGNED, weatherForecastSamples30_weather TINYINT UNSIGNED, weatherForecastSamples30_trackTemperature TINYINT UNSIGNED, weatherForecastSamples30_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples30_airTemperature TINYINT UNSIGNED, weatherForecastSamples30_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples30_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples31_sessionType TINYINT UNSIGNED, weatherForecastSamples31_timeOffset TINYINT UNSIGNED, weatherForecastSamples31_weather TINYINT UNSIGNED, weatherForecastSamples31_trackTemperature TINYINT UNSIGNED, weatherForecastSamples31_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples31_airTemperature TINYINT UNSIGNED, weatherForecastSamples31_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples31_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples32_sessionType TINYINT UNSIGNED, weatherForecastSamples32_timeOffset TINYINT UNSIGNED, weatherForecastSamples32_weather TINYINT UNSIGNED, weatherForecastSamples32_trackTemperature TINYINT UNSIGNED, weatherForecastSamples32_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples32_airTemperature TINYINT UNSIGNED, weatherForecastSamples32_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples32_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples33_sessionType TINYINT UNSIGNED, weatherForecastSamples33_timeOffset TINYINT UNSIGNED, weatherForecastSamples33_weather TINYINT UNSIGNED, weatherForecastSamples33_trackTemperature TINYINT UNSIGNED, weatherForecastSamples33_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples33_airTemperature TINYINT UNSIGNED, weatherForecastSamples33_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples33_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples34_sessionType TINYINT UNSIGNED, weatherForecastSamples34_timeOffset TINYINT UNSIGNED, weatherForecastSamples34_weather TINYINT UNSIGNED, weatherForecastSamples34_trackTemperature TINYINT UNSIGNED, weatherForecastSamples34_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples34_airTemperature TINYINT UNSIGNED, weatherForecastSamples34_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples34_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples35_sessionType TINYINT UNSIGNED, weatherForecastSamples35_timeOffset TINYINT UNSIGNED, weatherForecastSamples35_weather TINYINT UNSIGNED, weatherForecastSamples35_trackTemperature TINYINT UNSIGNED, weatherForecastSamples35_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples35_airTemperature TINYINT UNSIGNED, weatherForecastSamples35_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples35_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples36_sessionType TINYINT UNSIGNED, weatherForecastSamples36_timeOffset TINYINT UNSIGNED, weatherForecastSamples36_weather TINYINT UNSIGNED, weatherForecastSamples36_trackTemperature TINYINT UNSIGNED, weatherForecastSamples36_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples36_airTemperature TINYINT UNSIGNED, weatherForecastSamples36_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples36_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples37_sessionType TINYINT UNSIGNED, weatherForecastSamples37_timeOffset TINYINT UNSIGNED, weatherForecastSamples37_weather TINYINT UNSIGNED, weatherForecastSamples37_trackTemperature TINYINT UNSIGNED, weatherForecastSamples37_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples37_airTemperature TINYINT UNSIGNED, weatherForecastSamples37_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples37_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples38_sessionType TINYINT UNSIGNED, weatherForecastSamples38_timeOffset TINYINT UNSIGNED, weatherForecastSamples38_weather TINYINT UNSIGNED, weatherForecastSamples38_trackTemperature TINYINT UNSIGNED, weatherForecastSamples38_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples38_airTemperature TINYINT UNSIGNED, weatherForecastSamples38_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples38_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples39_sessionType TINYINT UNSIGNED, weatherForecastSamples39_timeOffset TINYINT UNSIGNED, weatherForecastSamples39_weather TINYINT UNSIGNED, weatherForecastSamples39_trackTemperature TINYINT UNSIGNED, weatherForecastSamples39_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples39_airTemperature TINYINT UNSIGNED, weatherForecastSamples39_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples39_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples40_sessionType TINYINT UNSIGNED, weatherForecastSamples40_timeOffset TINYINT UNSIGNED, weatherForecastSamples40_weather TINYINT UNSIGNED, weatherForecastSamples40_trackTemperature TINYINT UNSIGNED, weatherForecastSamples40_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples40_airTemperature TINYINT UNSIGNED, weatherForecastSamples40_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples40_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples41_sessionType TINYINT UNSIGNED, weatherForecastSamples41_timeOffset TINYINT UNSIGNED, weatherForecastSamples41_weather TINYINT UNSIGNED, weatherForecastSamples41_trackTemperature TINYINT UNSIGNED, weatherForecastSamples41_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples41_airTemperature TINYINT UNSIGNED, weatherForecastSamples41_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples41_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples42_sessionType TINYINT UNSIGNED, weatherForecastSamples42_timeOffset TINYINT UNSIGNED, weatherForecastSamples42_weather TINYINT UNSIGNED, weatherForecastSamples42_trackTemperature TINYINT UNSIGNED, weatherForecastSamples42_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples42_airTemperature TINYINT UNSIGNED, weatherForecastSamples42_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples42_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples43_sessionType TINYINT UNSIGNED, weatherForecastSamples43_timeOffset TINYINT UNSIGNED, weatherForecastSamples43_weather TINYINT UNSIGNED, weatherForecastSamples43_trackTemperature TINYINT UNSIGNED, weatherForecastSamples43_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples43_airTemperature TINYINT UNSIGNED, weatherForecastSamples43_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples43_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples44_sessionType TINYINT UNSIGNED, weatherForecastSamples44_timeOffset TINYINT UNSIGNED, weatherForecastSamples44_weather TINYINT UNSIGNED, weatherForecastSamples44_trackTemperature TINYINT UNSIGNED, weatherForecastSamples44_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples44_airTemperature TINYINT UNSIGNED, weatherForecastSamples44_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples44_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples45_sessionType TINYINT UNSIGNED, weatherForecastSamples45_timeOffset TINYINT UNSIGNED, weatherForecastSamples45_weather TINYINT UNSIGNED, weatherForecastSamples45_trackTemperature TINYINT UNSIGNED, weatherForecastSamples45_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples45_airTemperature TINYINT UNSIGNED, weatherForecastSamples45_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples45_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples46_sessionType TINYINT UNSIGNED, weatherForecastSamples46_timeOffset TINYINT UNSIGNED, weatherForecastSamples46_weather TINYINT UNSIGNED, weatherForecastSamples46_trackTemperature TINYINT UNSIGNED, weatherForecastSamples46_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples46_airTemperature TINYINT UNSIGNED, weatherForecastSamples46_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples46_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples47_sessionType TINYINT UNSIGNED, weatherForecastSamples47_timeOffset TINYINT UNSIGNED, weatherForecastSamples47_weather TINYINT UNSIGNED, weatherForecastSamples47_trackTemperature TINYINT UNSIGNED, weatherForecastSamples47_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples47_airTemperature TINYINT UNSIGNED, weatherForecastSamples47_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples47_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples48_sessionType TINYINT UNSIGNED, weatherForecastSamples48_timeOffset TINYINT UNSIGNED, weatherForecastSamples48_weather TINYINT UNSIGNED, weatherForecastSamples48_trackTemperature TINYINT UNSIGNED, weatherForecastSamples48_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples48_airTemperature TINYINT UNSIGNED, weatherForecastSamples48_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples48_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples49_sessionType TINYINT UNSIGNED, weatherForecastSamples49_timeOffset TINYINT UNSIGNED, weatherForecastSamples49_weather TINYINT UNSIGNED, weatherForecastSamples49_trackTemperature TINYINT UNSIGNED, weatherForecastSamples49_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples49_airTemperature TINYINT UNSIGNED, weatherForecastSamples49_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples49_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples50_sessionType TINYINT UNSIGNED, weatherForecastSamples50_timeOffset TINYINT UNSIGNED, weatherForecastSamples50_weather TINYINT UNSIGNED, weatherForecastSamples50_trackTemperature TINYINT UNSIGNED, weatherForecastSamples50_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples50_airTemperature TINYINT UNSIGNED, weatherForecastSamples50_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples50_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples51_sessionType TINYINT UNSIGNED, weatherForecastSamples51_timeOffset TINYINT UNSIGNED, weatherForecastSamples51_weather TINYINT UNSIGNED, weatherForecastSamples51_trackTemperature TINYINT UNSIGNED, weatherForecastSamples51_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples51_airTemperature TINYINT UNSIGNED, weatherForecastSamples51_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples51_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples52_sessionType TINYINT UNSIGNED, weatherForecastSamples52_timeOffset TINYINT UNSIGNED, weatherForecastSamples52_weather TINYINT UNSIGNED, weatherForecastSamples52_trackTemperature TINYINT UNSIGNED, weatherForecastSamples52_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples52_airTemperature TINYINT UNSIGNED, weatherForecastSamples52_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples52_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples53_sessionType TINYINT UNSIGNED, weatherForecastSamples53_timeOffset TINYINT UNSIGNED, weatherForecastSamples53_weather TINYINT UNSIGNED, weatherForecastSamples53_trackTemperature TINYINT UNSIGNED, weatherForecastSamples53_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples53_airTemperature TINYINT UNSIGNED, weatherForecastSamples53_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples53_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples54_sessionType TINYINT UNSIGNED, weatherForecastSamples54_timeOffset TINYINT UNSIGNED, weatherForecastSamples54_weather TINYINT UNSIGNED, weatherForecastSamples54_trackTemperature TINYINT UNSIGNED, weatherForecastSamples54_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples54_airTemperature TINYINT UNSIGNED, weatherForecastSamples54_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples54_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples55_sessionType TINYINT UNSIGNED, weatherForecastSamples55_timeOffset TINYINT UNSIGNED, weatherForecastSamples55_weather TINYINT UNSIGNED, weatherForecastSamples55_trackTemperature TINYINT UNSIGNED, weatherForecastSamples55_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples55_airTemperature TINYINT UNSIGNED, weatherForecastSamples55_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples55_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples56_sessionType TINYINT UNSIGNED, weatherForecastSamples56_timeOffset TINYINT UNSIGNED, weatherForecastSamples56_weather TINYINT UNSIGNED, weatherForecastSamples56_trackTemperature TINYINT UNSIGNED, weatherForecastSamples56_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples56_airTemperature TINYINT UNSIGNED, weatherForecastSamples56_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples56_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples57_sessionType TINYINT UNSIGNED, weatherForecastSamples57_timeOffset TINYINT UNSIGNED, weatherForecastSamples57_weather TINYINT UNSIGNED, weatherForecastSamples57_trackTemperature TINYINT UNSIGNED, weatherForecastSamples57_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples57_airTemperature TINYINT UNSIGNED, weatherForecastSamples57_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples57_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples58_sessionType TINYINT UNSIGNED, weatherForecastSamples58_timeOffset TINYINT UNSIGNED, weatherForecastSamples58_weather TINYINT UNSIGNED, weatherForecastSamples58_trackTemperature TINYINT UNSIGNED, weatherForecastSamples58_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples58_airTemperature TINYINT UNSIGNED, weatherForecastSamples58_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples58_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples59_sessionType TINYINT UNSIGNED, weatherForecastSamples59_timeOffset TINYINT UNSIGNED, weatherForecastSamples59_weather TINYINT UNSIGNED, weatherForecastSamples59_trackTemperature TINYINT UNSIGNED, weatherForecastSamples59_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples59_airTemperature TINYINT UNSIGNED, weatherForecastSamples59_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples59_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples60_sessionType TINYINT UNSIGNED, weatherForecastSamples60_timeOffset TINYINT UNSIGNED, weatherForecastSamples60_weather TINYINT UNSIGNED, weatherForecastSamples60_trackTemperature TINYINT UNSIGNED, weatherForecastSamples60_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples60_airTemperature TINYINT UNSIGNED, weatherForecastSamples60_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples60_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples61_sessionType TINYINT UNSIGNED, weatherForecastSamples61_timeOffset TINYINT UNSIGNED, weatherForecastSamples61_weather TINYINT UNSIGNED, weatherForecastSamples61_trackTemperature TINYINT UNSIGNED, weatherForecastSamples61_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples61_airTemperature TINYINT UNSIGNED, weatherForecastSamples61_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples61_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples62_sessionType TINYINT UNSIGNED, weatherForecastSamples62_timeOffset TINYINT UNSIGNED, weatherForecastSamples62_weather TINYINT UNSIGNED, weatherForecastSamples62_trackTemperature TINYINT UNSIGNED, weatherForecastSamples62_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples62_airTemperature TINYINT UNSIGNED, weatherForecastSamples62_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples62_rainPercentage TINYINT UNSIGNED,
    weatherForecastSamples63_sessionType TINYINT UNSIGNED, weatherForecastSamples63_timeOffset TINYINT UNSIGNED, weatherForecastSamples63_weather TINYINT UNSIGNED, weatherForecastSamples63_trackTemperature TINYINT UNSIGNED, weatherForecastSamples63_trackTemperatureChange TINYINT UNSIGNED, weatherForecastSamples63_airTemperature TINYINT UNSIGNED, weatherForecastSamples63_airTemperatureChange TINYINT UNSIGNED, weatherForecastSamples63_rainPercentage TINYINT UNSIGNED,
    forecastAccuracy TINYINT UNSIGNED,
    aiDifficulty TINYINT UNSIGNED,
    seasonLinkIdentifier INT UNSIGNED,
    weekendLinkIdentifier INT UNSIGNED,
    sessionLinkIdentifier INT UNSIGNED,
    pitStopWindowIdealLap TINYINT UNSIGNED,
    pitStopWindowLatestLap TINYINT UNSIGNED,
    pitStopRejoinPosition TINYINT UNSIGNED,
    steeringAssist TINYINT UNSIGNED,
    brakingAssist TINYINT UNSIGNED,
    gearboxAssist TINYINT UNSIGNED,
    pitAssist TINYINT UNSIGNED,
    pitReleaseAssist TINYINT UNSIGNED,
    ersAssist TINYINT UNSIGNED,
    drsAssist TINYINT UNSIGNED,
    dynamicRacingLine TINYINT UNSIGNED,
    dynamicRacingLineType TINYINT UNSIGNED,
    gameMode TINYINT UNSIGNED,
    ruleSet TINYINT UNSIGNED,
    timeOfDay INT UNSIGNED,
    sessionLength TINYINT UNSIGNED,
    speedUnitsLeadPlayer TINYINT UNSIGNED,
    temperatureUnitsLeadPlayer TINYINT UNSIGNED,
    speedUnitsSecondaryPlayer TINYINT UNSIGNED,
    temperatureUnitsSecondaryPlayer TINYINT UNSIGNED,
    numSafetyCarPeriods TINYINT UNSIGNED,
    numVirtualSafetyCarPeriods TINYINT UNSIGNED,
    numRedFlagPeriods TINYINT UNSIGNED,
    equalCarPerformance TINYINT UNSIGNED,
    recoveryMode TINYINT UNSIGNED,
    flashbackLimit TINYINT UNSIGNED,
    surfaceType TINYINT UNSIGNED,
    lowFuelMode TINYINT UNSIGNED,
    raceStarts TINYINT UNSIGNED,
    tyreTemperature TINYINT UNSIGNED,
    pitLaneTyreSim TINYINT UNSIGNED,
    carDamage TINYINT UNSIGNED,
    carDamageRate TINYINT UNSIGNED,
    collisions TINYINT UNSIGNED,
    collisionsOffForFirstLapOnly TINYINT UNSIGNED,
    mpUnsafePitRelease TINYINT UNSIGNED,
    mpOffForGriefing TINYINT UNSIGNED,
    cornerCuttingStringency TINYINT UNSIGNED,
    parcFermeRules TINYINT UNSIGNED,
    pitStopExperience TINYINT UNSIGNED,
    safetyCar TINYINT UNSIGNED,
    safetyCarExperience TINYINT UNSIGNED,
    formationLap TINYINT UNSIGNED,
    formationLapExperience TINYINT UNSIGNED,
    redFlags TINYINT UNSIGNED,
    affectsLicenceLevelSolo TINYINT UNSIGNED,
    affectsLicenceLevelMP TINYINT UNSIGNED,
    numSessionsInWeekend TINYINT UNSIGNED,
    weekendStructure0 TINYINT,
    weekendStructure1 TINYINT,
    weekendStructure2 TINYINT,
    weekendStructure3 TINYINT,
    weekendStructure4 TINYINT,
    weekendStructure5 TINYINT,
    weekendStructure6 TINYINT,
    weekendStructure7 TINYINT,
    weekendStructure8 TINYINT,
    weekendStructure9 TINYINT,
    weekendStructure10 TINYINT,
    weekendStructure11 TINYINT,
    sector2LapDistanceStart FLOAT,
    sector3LapDistanceStart FLOAT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS LAP (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lastLapTimeInMS INT UNSIGNED,
    currentLapTimeInMS INT UNSIGNED,
    sector1TimeMSPart SMALLINT UNSIGNED,
    sector1TimeMinutesPart TINYINT UNSIGNED,
    sector2TimeMSPart SMALLINT UNSIGNED,
    sector2TimeMinutesPart TINYINT UNSIGNED,
    deltaToCarInFrontMSPart SMALLINT UNSIGNED,
    deltaToCarInFrontMinutesPart TINYINT UNSIGNED,
    deltaToRaceLeaderMSPart SMALLINT UNSIGNED,
    deltaToRaceLeaderMinutesPart TINYINT UNSIGNED,
    lapDistance FLOAT,
    totalDistance FLOAT,
    safetyCarDelta FLOAT,
    carPosition TINYINT UNSIGNED,
    currentLapNum TINYINT UNSIGNED,
    pitStatus TINYINT UNSIGNED,
    numPitStops TINYINT UNSIGNED,
    sector TINYINT UNSIGNED,
    currentLapInvalid TINYINT UNSIGNED,
    penalties TINYINT UNSIGNED,
    totalWarnings TINYINT UNSIGNED,
    cornerCuttingWarnings TINYINT UNSIGNED,
    numUnservedDriveThroughPens TINYINT UNSIGNED,
    numUnservedStopGoPens TINYINT UNSIGNED,
    gridPosition TINYINT UNSIGNED,
    driverStatus TINYINT UNSIGNED,
    resultStatus TINYINT UNSIGNED,
    pitLaneTimerActive TINYINT UNSIGNED,
    pitLaneTimeInLaneInMS SMALLINT UNSIGNED,
    pitStopTimerInMS SMALLINT UNSIGNED,
    pitStopShouldServePen TINYINT UNSIGNED,
    speedTrapFastestSpeed FLOAT,
    speedTrapFastestLap TINYINT UNSIGNED,
    timeTrialPBCarIdx TINYINT UNSIGNED,
    timeTrialRivalCarIdx TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS EVENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    eventStringCode CHAR(4),
    fastestLap_vehicleIdx TINYINT UNSIGNED,
    fastestLap_lapTime FLOAT,
    retirement_vehicleIdx TINYINT UNSIGNED,
    teamMateInPits_vehicleIdx TINYINT UNSIGNED,
    raceWinner_vehicleIdx TINYINT UNSIGNED,
    penalty_penaltyType TINYINT UNSIGNED,
    penalty_infringementType TINYINT UNSIGNED,
    penalty_vehicleIdx TINYINT UNSIGNED,
    penalty_otherVehicleIdx TINYINT UNSIGNED,
    penalty_time TINYINT UNSIGNED,
    penalty_lapNum TINYINT UNSIGNED,
    penalty_placesGained TINYINT UNSIGNED,
    speedTrap_vehicleIdx TINYINT UNSIGNED,
    speedTrap_speed FLOAT,
    speedTrap_isOverallFastest TINYINT UNSIGNED,
    speedTrap_isDriverFastest TINYINT UNSIGNED,
    speedTrap_fastestVehicleIdx TINYINT UNSIGNED,
    speedTrap_fastestSpeed FLOAT,
    startLights_numLights TINYINT UNSIGNED,
    driveThroughPenaltyServed_vehicleIdx TINYINT UNSIGNED,
    stopGoPenaltyServed_vehicleIdx TINYINT UNSIGNED,
    flashback_flashbackFrameIdentifier INT UNSIGNED,
    flashback_flashbackSessionTime FLOAT,
    buttons_buttonStatus INT UNSIGNED,
    overtake_overtakingVehicleIdx TINYINT UNSIGNED,
    overtake_beingOvertakenVehicleIdx TINYINT UNSIGNED,
    safetyCar_safetyCarType TINYINT UNSIGNED,
    safetyCar_EventType TINYINT UNSIGNED,
    collision_vehicle1Idx TINYINT UNSIGNED,
    collision_vehicle2Idx TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS PARTICIPANTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numActiveCars TINYINT UNSIGNED,
    aiControlled TINYINT UNSIGNED,
    driverId TINYINT UNSIGNED,
    networkId TINYINT UNSIGNED,
    teamId TINYINT UNSIGNED,
    myTeam TINYINT UNSIGNED,
    raceNumber TINYINT UNSIGNED,
    nationality TINYINT UNSIGNED,
    name VARCHAR(48),
    yourTelemetry TINYINT UNSIGNED,
    showOnlineNames TINYINT UNSIGNED,
    techLevel SMALLINT UNSIGNED,
    platform TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CARSETUP (
    id INT AUTO_INCREMENT PRIMARY KEY,
    frontWing TINYINT UNSIGNED,
    rearWing TINYINT UNSIGNED,
    onThrottle TINYINT UNSIGNED,
    offThrottle TINYINT UNSIGNED,
    frontCamber FLOAT,
    rearCamber FLOAT,
    frontToe FLOAT,
    rearToe FLOAT,
    frontSuspension TINYINT UNSIGNED,
    rearSuspension TINYINT UNSIGNED,
    frontAntiRollBar TINYINT UNSIGNED,
    rearAntiRollBar TINYINT UNSIGNED,
    frontSuspensionHeight TINYINT UNSIGNED,
    rearSuspensionHeight TINYINT UNSIGNED,
    brakePressure TINYINT UNSIGNED,
    brakeBias TINYINT UNSIGNED,
    engineBraking TINYINT UNSIGNED,
    rearLeftTyrePressure FLOAT,
    rearRightTyrePressure FLOAT,
    frontLeftTyrePressure FLOAT,
    frontRightTyrePressure FLOAT,
    ballast TINYINT UNSIGNED,
    fuelLoad FLOAT,
    nextFrontWingValue FLOAT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CARTELEMETRY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    speed SMALLINT UNSIGNED,
    throttle FLOAT,
    steer FLOAT,
    brake FLOAT,
    clutch TINYINT UNSIGNED,
    gear TINYINT,
    engineRPM SMALLINT UNSIGNED,
    drs TINYINT UNSIGNED,
    revLightsPercent TINYINT UNSIGNED,
    revLightsBitValue SMALLINT UNSIGNED,
    brakesTemperature0 SMALLINT UNSIGNED,
    brakesTemperature1 SMALLINT UNSIGNED,
    brakesTemperature2 SMALLINT UNSIGNED,
    brakesTemperature3 SMALLINT UNSIGNED,
    tyresSurfaceTemperature0 TINYINT UNSIGNED,
    tyresSurfaceTemperature1 TINYINT UNSIGNED,
    tyresSurfaceTemperature2 TINYINT UNSIGNED,
    tyresSurfaceTemperature3 TINYINT UNSIGNED,
    tyresInnerTemperature0 TINYINT UNSIGNED,
    tyresInnerTemperature1 TINYINT UNSIGNED,
    tyresInnerTemperature2 TINYINT UNSIGNED,
    tyresInnerTemperature3 TINYINT UNSIGNED,
    engineTemperature SMALLINT UNSIGNED,
    tyresPressure0 FLOAT,
    tyresPressure1 FLOAT,
    tyresPressure2 FLOAT,
    tyresPressure3 FLOAT,
    surfaceType0 TINYINT UNSIGNED,
    surfaceType1 TINYINT UNSIGNED,
    surfaceType2 TINYINT UNSIGNED,
    surfaceType3 TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CARSTATUS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tractionControl TINYINT UNSIGNED,
    antiLockBrakes TINYINT UNSIGNED,
    fuelMix TINYINT UNSIGNED,
    frontBrakeBias TINYINT UNSIGNED,
    pitLimiterStatus TINYINT UNSIGNED,
    fuelInTank FLOAT,
    fuelCapacity FLOAT,
    fuelRemainingLaps FLOAT,
    maxRPM SMALLINT UNSIGNED,
    idleRPM SMALLINT UNSIGNED,
    maxGears TINYINT UNSIGNED,
    drsAllowed TINYINT UNSIGNED,
    drsActivationDistance SMALLINT UNSIGNED,
    actualTyreCompound TINYINT UNSIGNED,
    visualTyreCompound TINYINT UNSIGNED,
    tyresAgeLaps TINYINT UNSIGNED,
    vehicleFiaFlags TINYINT,
    enginePowerICE FLOAT,
    enginePowerMGUK FLOAT,
    ersStoreEnergy FLOAT,
    ersDeployMode TINYINT UNSIGNED,
    ersHarvestedThisLapMGUK FLOAT,
    ersHarvestedThisLapMGUH FLOAT,
    ersDeployedThisLap FLOAT,
    networkPaused TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FINALCLASSIFICATION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numCars TINYINT UNSIGNED,
    position TINYINT UNSIGNED,
    numLaps TINYINT UNSIGNED,
    gridPosition TINYINT UNSIGNED,
    points TINYINT UNSIGNED,
    numPitStops TINYINT UNSIGNED,
    resultStatus TINYINT UNSIGNED,
    bestLapTimeInMS INT UNSIGNED,
    totalRaceTime DOUBLE,
    penaltiesTime TINYINT UNSIGNED,
    numPenalties TINYINT UNSIGNED,
    numTyreStints TINYINT UNSIGNED,
    tyreStintsActual0 TINYINT UNSIGNED,
    tyreStintsActual1 TINYINT UNSIGNED,
    tyreStintsActual2 TINYINT UNSIGNED,
    tyreStintsActual3 TINYINT UNSIGNED,
    tyreStintsActual4 TINYINT UNSIGNED,
    tyreStintsActual5 TINYINT UNSIGNED,
    tyreStintsActual6 TINYINT UNSIGNED,
    tyreStintsActual7 TINYINT UNSIGNED,
    tyreStintsVisual0 TINYINT UNSIGNED,
    tyreStintsVisual1 TINYINT UNSIGNED,
    tyreStintsVisual2 TINYINT UNSIGNED,
    tyreStintsVisual3 TINYINT UNSIGNED,
    tyreStintsVisual4 TINYINT UNSIGNED,
    tyreStintsVisual5 TINYINT UNSIGNED,
    tyreStintsVisual6 TINYINT UNSIGNED,
    tyreStintsVisual7 TINYINT UNSIGNED,
    tyreStintsEndLaps0 TINYINT UNSIGNED,
    tyreStintsEndLaps1 TINYINT UNSIGNED,
    tyreStintsEndLaps2 TINYINT UNSIGNED,
    tyreStintsEndLaps3 TINYINT UNSIGNED,
    tyreStintsEndLaps4 TINYINT UNSIGNED,
    tyreStintsEndLaps5 TINYINT UNSIGNED,
    tyreStintsEndLaps6 TINYINT UNSIGNED,
    tyreStintsEndLaps7 TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS LOBBYINFO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numPlayers TINYINT UNSIGNED,
    aiControlled TINYINT UNSIGNED,
    teamId TINYINT UNSIGNED,
    nationality TINYINT UNSIGNED,
    platform TINYINT UNSIGNED,
    name VARCHAR(48),
    carNumber TINYINT UNSIGNED,
    yourTelemetry TINYINT UNSIGNED,
    showOnlineNames TINYINT UNSIGNED,
    techLevel SMALLINT UNSIGNED,
    readyStatus TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CARDAMAGE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tyresWear0 FLOAT,
    tyresWear1 FLOAT,
    tyresWear2 FLOAT,
    tyresWear3 FLOAT,
    tyresDamage0 TINYINT UNSIGNED,
    tyresDamage1 TINYINT UNSIGNED,
    tyresDamage2 TINYINT UNSIGNED,
    tyresDamage3 TINYINT UNSIGNED,
    brakesDamage0 TINYINT UNSIGNED,
    brakesDamage1 TINYINT UNSIGNED,
    brakesDamage2 TINYINT UNSIGNED,
    brakesDamage3 TINYINT UNSIGNED,
    frontLeftWingDamage TINYINT UNSIGNED,
    frontRightWingDamage TINYINT UNSIGNED,
    rearWingDamage TINYINT UNSIGNED,
    floorDamage TINYINT UNSIGNED,
    diffuserDamage TINYINT UNSIGNED,
    sidepodDamage TINYINT UNSIGNED,
    drsFault TINYINT UNSIGNED,
    ersFault TINYINT UNSIGNED,
    gearBoxDamage TINYINT UNSIGNED,
    engineDamage TINYINT UNSIGNED,
    engineMGUHWear TINYINT UNSIGNED,
    engineESWear TINYINT UNSIGNED,
    engineCEWear TINYINT UNSIGNED,
    engineICEWear TINYINT UNSIGNED,
    engineMGUKWear TINYINT UNSIGNED,
    engineTCWear TINYINT UNSIGNED,
    engineBlown TINYINT UNSIGNED,
    engineSeized TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_damage_timestamp (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SESSIONHISTORY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    carIdx TINYINT UNSIGNED,
    numLaps TINYINT UNSIGNED,
    numTyreStints TINYINT UNSIGNED,
    bestLapTimeLapNum TINYINT UNSIGNED,
    bestSector1LapNum TINYINT UNSIGNED,
    bestSector2LapNum TINYINT UNSIGNED,
    bestSector3LapNum TINYINT UNSIGNED,
    tyreStintHistory0_endLap TINYINT UNSIGNED, tyreStintHistory0_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory0_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory1_endLap TINYINT UNSIGNED, tyreStintHistory1_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory1_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory2_endLap TINYINT UNSIGNED, tyreStintHistory2_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory2_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory3_endLap TINYINT UNSIGNED, tyreStintHistory3_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory3_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory4_endLap TINYINT UNSIGNED, tyreStintHistory4_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory4_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory5_endLap TINYINT UNSIGNED, tyreStintHistory5_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory5_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory6_endLap TINYINT UNSIGNED, tyreStintHistory6_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory6_tyreVisualCompound TINYINT UNSIGNED,
    tyreStintHistory7_endLap TINYINT UNSIGNED, tyreStintHistory7_tyreActualCompound TINYINT UNSIGNED, tyreStintHistory7_tyreVisualCompound TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
CREATE TABLE IF NOT EXISTS SESSIONHISTORYLAPHISTORY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lapTimeInMS INT UNSIGNED,
    sector1TimeInMS SMALLINT UNSIGNED,
    sector1TimeMinutes TINYINT UNSIGNED,
    sector2TimeInMS SMALLINT UNSIGNED,
    sector2TimeMinutes TINYINT UNSIGNED,
    sector3TimeInMS SMALLINT UNSIGNED,
    sector3TimeMinutes TINYINT UNSIGNED,
    lapValidBitFlags TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS TYRESET (
    id INT AUTO_INCREMENT PRIMARY KEY,
    carIdx TINYINT UNSIGNED,
    actualTyreCompound TINYINT UNSIGNED,
    visualTyreCompound TINYINT UNSIGNED,
    wear TINYINT UNSIGNED,
    available TINYINT UNSIGNED,
    recommendedSession TINYINT UNSIGNED,
    lifeSpan TINYINT UNSIGNED,
    usableLife TINYINT UNSIGNED,
    lapDeltaTime SMALLINT,
    fitted TINYINT UNSIGNED,
    fittedIdx TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS MOTIONEX ( -- wheel order (RL, RR, FL, FR)
    id INT AUTO_INCREMENT PRIMARY KEY,
    suspensionPosition0 FLOAT,
    suspensionPosition1 FLOAT,
    suspensionPosition2 FLOAT,
    suspensionPosition3 FLOAT,
    suspensionVelocity0 FLOAT,
    suspensionVelocity1 FLOAT,
    suspensionVelocity2 FLOAT,
    suspensionVelocity3 FLOAT,
    suspensionAcceleration0 FLOAT,
    suspensionAcceleration1 FLOAT,
    suspensionAcceleration2 FLOAT,
    suspensionAcceleration3 FLOAT,
    wheelSpeed0 FLOAT,
    wheelSpeed1 FLOAT,
    wheelSpeed2 FLOAT,
    wheelSpeed3 FLOAT,
    wheelSlipRatio0 FLOAT,
    wheelSlipRatio1 FLOAT,
    wheelSlipRatio2 FLOAT,
    wheelSlipRatio3 FLOAT,
    wheelSlipAngle0 FLOAT,
    wheelSlipAngle1 FLOAT,
    wheelSlipAngle2 FLOAT,
    wheelSlipAngle3 FLOAT,
    wheelLatForce0 FLOAT,
    wheelLatForce1 FLOAT,
    wheelLatForce2 FLOAT,
    wheelLatForce3 FLOAT,
    wheelLongForce0 FLOAT,
    wheelLongForce1 FLOAT,
    wheelLongForce2 FLOAT,
    wheelLongForce3 FLOAT,
    heightOfCOGAboveGround FLOAT,
    localVelocityX FLOAT,
    localVelocityY FLOAT,
    localVelocityZ FLOAT,
    angularVelocityX FLOAT,
    angularVelocityY FLOAT,
    angularVelocityZ FLOAT,
    angularAccelerationX FLOAT,
    angularAccelerationY FLOAT,
    angularAccelerationZ FLOAT,
    frontWheelsAngle FLOAT,
    wheelVertForce0 FLOAT,
    wheelVertForce1 FLOAT,
    wheelVertForce2 FLOAT,
    wheelVertForce3 FLOAT,
    frontAeroHeight FLOAT,
    rearAeroHeight FLOAT,
    frontRollAngle FLOAT,
    rearRollAngle FLOAT,
    chassisYaw FLOAT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS TIMETRIAL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    playerSessionBestDataSet_carIdx TINYINT UNSIGNED,
    playerSessionBestDataSet_teamId TINYINT UNSIGNED,
    playerSessionBestDataSet_lapTimeInMS INT UNSIGNED,
    playerSessionBestDataSet_sector1TimeInMS INT UNSIGNED,
    playerSessionBestDataSet_sector2TimeInMS INT UNSIGNED,
    playerSessionBestDataSet_sector3TimeInMS INT UNSIGNED,
    playerSessionBestDataSet_tractionControl TINYINT UNSIGNED,
    playerSessionBestDataSet_gearboxAssist TINYINT UNSIGNED,
    playerSessionBestDataSet_antiLockBrakes TINYINT UNSIGNED,
    playerSessionBestDataSet_equalCarPerformance TINYINT UNSIGNED,
    playerSessionBestDataSet_customSetup TINYINT UNSIGNED,
    playerSessionBestDataSet_valid TINYINT UNSIGNED,
    personalBestDataSet_carIdx TINYINT UNSIGNED,
    personalBestDataSet_teamId TINYINT UNSIGNED,
    personalBestDataSet_lapTimeInMS INT UNSIGNED,
    personalBestDataSet_sector1TimeInMS INT UNSIGNED,
    personalBestDataSet_sector2TimeInMS INT UNSIGNED,
    personalBestDataSet_sector3TimeInMS INT UNSIGNED,
    personalBestDataSet_tractionControl TINYINT UNSIGNED,
    personalBestDataSet_gearboxAssist TINYINT UNSIGNED,
    personalBestDataSet_antiLockBrakes TINYINT UNSIGNED,
    personalBestDataSet_equalCarPerformance TINYINT UNSIGNED,
    personalBestDataSet_customSetup TINYINT UNSIGNED,
    personalBestDataSet_valid TINYINT UNSIGNED,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp_desc (timestamp DESC)
);